# 1. Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: search-backend
  name: search-backend
  namespace: dinesh
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: search-backend
  template:
    metadata:
      labels:
        app: search-backend
    spec:
      containers:
      - name: search-backend
        image: dineshsonachalam/tech-courses-search-engine-backend:latest
        imagePullPolicy: Always          
        ports:
        - containerPort: 8000   
          name: search-backend   
---
# 2. Service
apiVersion: v1
kind: Service
metadata:
  name: search-backend
  namespace: dinesh
spec:
  ports:
    - protocol: TCP
      name: web
      port: 8000
  selector:
    app: search-backend