# 1. Statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
  namespace: dinesh
spec:
  selector:
    matchLabels:
      app: es # has to match .spec.template.metadata.labels
  serviceName: "es"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: es # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh","-c"]
        args: ["sysctl -w vm.max_map_count=262144; chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
          - name: es-data
            mountPath: /usr/share/elasticsearch/data
      containers:
      - name: es
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
        env:
        - name: discovery.type
          value: "single-node"
        ports:
        - containerPort: 9200
          name: es
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
---
# 2. Service
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: dinesh
  labels:
    app: es
spec:
  ports:
  - port: 9200
    name: web
  selector:
    app: es