name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    tags:
      - latest
  
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Build backend and frontend image
        run: |
          npm i --prefix frontend
          npm run build --prefix frontend
          docker build --no-cache -t dineshsonachalam/tech-courses-search-engine-backend:latest -f backend.Dockerfile .
          docker build --no-cache -t dineshsonachalam/tech-courses-search-engine-frontend:latest -f frontend.Dockerfile .  

      - name: Log into registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: |
          docker push dineshsonachalam/tech-courses-search-engine-backend:latest
          docker push dineshsonachalam/tech-courses-search-engine-frontend:latest
