name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    tags:
      - latest
  
jobs:
  integration-tests:
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v2
        - name: Start the elasticsearch docker container
          run: docker run -d -p 9200:9200 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.12.0

        - name: Install backend and frontend dependencies
          run: |
            pip3 install -r backend/requirements.txt
            npm i --prefix frontend
        
        - name: Start the backend and frontend application in the background
          run: |
            python3 backend/main.py &
            npm run start --prefix frontend &
            curl --location --request GET 'http://0.0.0.0:8000/autocomplete?query=kubernetes'

        - name: API testing
          run: pytest backend -s

        - name: Cypress End to End testing
          uses: cypress-io/github-action@v2
          with:
            working-directory: frontend


  upload-docker-image:
    needs: integration-tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Build backend and frontend image
        run: |
          npm i --prefix frontend
          npm run build --prefix frontend
          docker build --no-cache -t dineshsonachalam/tech-courses-search-engine-backend:latest -f backend.Dockerfile .
          docker build --no-cache -t dineshsonachalam/tech-courses-search-engine-frontend:latest -f frontend.Dockerfile .  

      - name: Log into registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: |
          docker push dineshsonachalam/tech-courses-search-engine-backend:latest
          docker push dineshsonachalam/tech-courses-search-engine-frontend:latest
